import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Dotting } from "dotting";
import { useCallback } from "react";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const testOpenAi = useCallback(async () => {
    const response = await axios.post("api/openai/dalle", {
      queryPrompt: "Hello world",
    });
    console.log(response);
    const { data } = response;
    console.log(data);
    const imgArray: Array<{ url: string }> = data.data;
    imgArray.forEach((element) => console.log(element.url));
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Dotting width={300} height={300} />
        <button onClick={testOpenAi}>Test</button>
      </main>
    </>
  );
}
